version: "3.8"
services:
  prisma-db:
    container_name: twitter-giveaway-api-db
    image: postgres:12
    ports:
      - "5403:5432"
    volumes:
      - prisma-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: twitter-giveaway-api
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
  prisma-test-db:
    container_name: twitter-giveaway-api-test-db
    image: postgres:12
    ports:
      - "5402:5432"
    volumes:
      - prisma-test-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: twitter-giveaway-api-test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
volumes:
  prisma-store:
    driver: local
  prisma-test-store:
    driver: local
